### PR TITLE
fix(extractor): Default value handling for props with aliasing

### LINKED ISSUE #52: Default values not recognized when using aliasing
With aliasing:

```svelte
<script lang="ts">
  let { a: b = 3 }: { a: number } = $props();
</script>
```

```json
{
  "exports": [],
  "isLegacy": false,
  "props": [
    [
      "a",
      {
        "tags": [],
        "isBindable": false,
        "isExtended": true,
        "isOptional": false,
        "type": {
          "kind": "number"
        },
        "sources": [
          "src/Demo.svelte"
        ]
      }
    ]
  ]
}
```

Without aliasing:

```svelte
<script lang="ts">
  let { a = 3 }: { a: number } = $props();
</script>
```

```json
{
  "exports": [],
  "isLegacy": false,
  "props": [
    [
      "a",
      {
        "tags": [],
        "isBindable": false,
        "isExtended": true,
        "isOptional": false,
        "type": {
          "kind": "number"
        },
        "default": {
          "kind": "literal",
          "subkind": "number",
          "value": 3
        },
        "sources": [
          "src/Demo.svelte"
        ]
      }
    ]
  ]
}
```

### PR DESCRIPTION
**Pull request by ciscorn**
Fixes #52 

```svelte
<script lang="ts">
  let { class: className = "foobar" }: {
    class?: string
  } = $props();
</script>
```

```json
{
  "exports": [],
  "isLegacy": false,
  "props": [
    [
      "class",
      {
        "tags": [],
        "isBindable": false,
        "isExtended": true,
        "isOptional": true,
        "type": {
          "kind": "union",
          "types": [
            {
              "kind": "undefined"
            },
            {
              "kind": "string"
            }
          ],
          "nonNullable": {
            "kind": "string"
          }
        },
        "default": {
          "kind": "literal",
          "subkind": "string",
          "value": "foobar"
        },
        "sources": [
          "src/Demo.svelte"
        ]
      }
    ]
  ]
}
```

### CODE REVIEW

File: packages/extractor/src/extractor/mod.js [hunk 1]
```diff
@@ -65,7 +65,7 @@ class Extractor {
 		if (this.#props_obj) {
 			for (const binding of this.#props_obj?.elements ?? []) {
 				if (!binding.initializer) continue;
-				const name = binding.name.getText();
+				const name = binding.propertyName?.getText() || binding.name.getText();
```
Comment (ciscorn) [inline packages/extractor/src/extractor/mod.js:68]: propertyName is undefined when no alias is used

**Review by xeho91 — APPROVED** [review]
That was quick!
