### PR TITLE
fix: Remove leading `/` of paths inside the `sources` set

### LINKED ISSUE #93: Non-extended prop(s) are not recognized
Reproduction link: https://output-pane.svelte-docgen.pages.dev/playground?input=EQHgzgxgTglgDgFwAQBsCGA7A5gXgDrAJgEB8eGeCMAtnAPZTIICecApkgN5IDKG87ZAF8kAMyh1qSAmABubFAjYEA3OUo16jJC3ZckACQAqAWQAyAIQCuCBHQwBBW7ABGNtmCQjxk6cDkKSgD0CmzUbBhEqupUkWxQomgQHAAKEnCebAAeShgAJp7G5ta29k4Iru6enDGUGPYAojkReWx5AFxIGFbULvEqSEFBOgAWMJ5gI3RWKHkYAOTIfUhQbBB0WPwAXm1IaJnN+W0xQjEobMhw6WCdaXQZOEgAJFf3YAAUAJRqGCBBkLBECRgEA

Prop `nonExtended` shouldn't be marked as `isExtended` by our analyzer.

Image

### PR DESCRIPTION
**Pull request by xeho91**
Resolves #93

Is a frigging leading path separator `/` again. So, I made a solution that we no longer include it in `sources` set paths

### CODE REVIEW

File: packages/svelte-docgen/src/shared.js [hunk 1]
```diff
@@ -133,7 +133,7 @@ export function get_sources(declarations, root_path_url) {
 			return d
 				.getSourceFile()
 				.fileName.replace(".tsx", "")
-				.replace(root_path_url.pathname, "");
+				.replace(root_path_url.pathname + pathe.sep, "");
```
Comment (xeho91) [inline packages/svelte-docgen/src/shared.js:136]: THe culprit is here.

**Review by ciscorn — APPROVED** [review]
nice catch!
